#!/usr/bin/expect
set timeout 3600
set host [lindex $argv 0]
set port [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]
set src_file [lindex $argv 4]
set dest_file [lindex $argv 5]
#set isdir [lindex $argv 6]

#if [[$isdir -eq 0]]; then
#    spawn scp $src_file $username@$host:$dest_file
#else
#    spawn scp -r $src_file $username@$host:$dest_file
#fi
spawn scp -r $src_file $username@$host:$dest_file
#spawn scp -P $port -r $username@$host:$src_file $dest_file
#expect {
 #"(yes/no)?" {
   #send "yes\n"
expect "*assword:" { send "$password\n"}
  #}
  #"*assword:" {
   #send "$password\n"
  #}
#}
expect "100%"
expect eof
